llm_model_path: models/mistral-7b-instruct-v0.1.Q4_K_M.gguf
chroma_db_dir: chromadb
embedding_model: sentence-transformers/all-MiniLM-L6-v2
chroma_collection: autoquest_knowledge
llm_context_size: 2048
llm_threads: 8
llm_temperature: 0.7
llm_max_tokens: 512
